### ISSUE TITLE
Can I fork this repo and translate to Chinese ？

### ISSUE THREAD

**Issue by JohannLai** [vinodotdev/node-to-rust#3]
hello, @jsoverson ,

Thank you for providing us with such a good ebook for learning Rust.  I want  Rust enthusiasts in China to also learn this ebook. Can I fork this repo and translate it into Chinese?  

thanks

**Comment by jsoverson** [comment]
Yes of course! If you finish this please let me know where your translation is located so I can link to it from here.

**Comment by JohannLai** [comment]
Thank you very much
